networks:
  my_network:
    driver: bridge

services:
  db:
    build: ./db
    container_name: db_image
    ports:
      - '4000:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    networks:
      - my_network

  db_repl:
    build: ./db_repl
    container_name: db_repl_image
    ports:
      - '4001:5432'
    depends_on:
      - db
    networks:
      - my_network

  tg_bot:
    build: ./tgbot
    container_name: telegram_bot
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgresql_master_data:
