FROM bitnami/postgresql:15-debian-12

# Установка переменных окружения
ENV POSTGRESQL_REPLICATION_MODE=master \
    POSTGRESQL_REPLICATION_USER=repl_user \
    POSTGRESQL_REPLICATION_PASSWORD=repl \
    POSTGRESQL_USERNAME=postgres \
    POSTGRESQL_PASSWORD=kali \
    POSTGRESQL_DATABASE=db_polyarush \
    POSTGRESQL_LOG_CONNECTIONS=on
